2ndYear/HVK_Reservation_Project/HVK/Models/EmployeeHomeViewModel.cs
namespace HVK.Models
{
    public class EmployeeHomeViewModel
    {
        public Hvkuser Employee { get; set; }
        public List<Pet> Pets { get; set; }
    }
}

2ndYear/HVK_Reservation_Project/HVK/Models/Hvkuser.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using static HVK.Models.CustomValidation;

namespace HVK.Models {
     
    public partial class Hvkuser {

       public Hvkuser() {
           Pets = new HashSet<Pet>();
       }
     

        public int HvkuserId { get; set; }
        [Required(ErrorMessage = "First Name is required")]
        [RegularExpression(@"^[a-zA-Z']+$", ErrorMessage = "Only letters and apostrophes are allowed in First Name")]
        [StringLength(25, ErrorMessage = "First Name can only have a max length of 25")]
       [Display(Name = "*First Name")]
       public string FirstName { get; set; }

        [Required(ErrorMessage = "Last Name is required")]
        [RegularExpression(@"^[a-zA-Z']+$", ErrorMessage = "Only letters and apostrophes are allowed in Last Name")]
        [StringLength(25, ErrorMessage = "Last Name can only have a max length of 25")]
       [Display(Name = "*Last Name")]
        public string LastName { get; set; }
        [NotNull]
        [StringLength(50, ErrorMessage = "Email can only have a max length of 50")]
        [EmailAddress(ErrorMessage = "Invalid email address")]
        [Display(Name = "Email Address")]
        public string? Email { get; set; }

       [RegularExpression(@"^\d{10}$", ErrorMessage = "Phone number must be 10 digits")]
       [StringLength(10, ErrorMessage = "Phone number can only have a max length of 10")]
        [Display(Name = "Phone Number")]
        public string? Phone { get; set; }

       [RegularExpression(@"^\d{10}$", ErrorMessage = "Cell Phone number must be 10 digits")]
       [StringLength(10, ErrorMessage = "Cell Phone number can only have a max length of 10")]
        //[OneContact(type)]
       [Display(Name = "Cell Phone Number")]
        public string? CellPhone { get; set; }

        //[Required(ErrorMessage = "Password is required")]
        [NotNull]
        [StringLength(50, ErrorMessage = "Password can only have a max length of 50")]
        public string? Password { get; set; }

        [StringLength(40, ErrorMessage = "Street can only have a max length of 40")]
        public string? Street { get; set; }

        [StringLength(25, ErrorMessage = "Street can only have a max length of 25")]
        public string? City { get; set; }

        public string? Province { get; set; }

        [RegularExpression(@"^[A-Za-z]\d[A-Za-z]\d[A-Za-z]\d$", ErrorMessage = "Invalid postal code format (A1A1A1)")]
        [StringLength(6, ErrorMessage = "Postal code can only have a max length of 6")]
        [Display(Name = "Postal Code")]
        public string? PostalCode { get; set; }

        //[Required(ErrorMessage = "First Name is required")]
        [NotNull]
        [RegularExpression(@"^[a-zA-Z']+$", ErrorMessage = "Only letters and apostrophes are allowed in First Name")]
        [StringLength(25, ErrorMessage = "First Name can only have a max length of 25")]
        [Display(Name = "First Name")]
        public string? EmergencyContactFirstName { get; set; }

        //[Required(ErrorMessage = "Last Name is required")]
        [NotNull]
        [RegularExpression(@"^[a-zA-Z']+$", ErrorMessage = "Only letters and apostrophes are allowed in Last Name")]
        [StringLength(25, ErrorMessage = "Last Name can only have a max length of 25")]
        [Display(Name = "Last Name")]
        public string? EmergencyContactLastName { get; set; }

        //[Required(ErrorMessage = "Phone number is required")]
        [NotNull]
        [RegularExpression(@"^\d{10}$", ErrorMessage = "Phone number must be 10 digits")]
       [StringLength(10, ErrorMessage = "Phone number can only have a max length of 10")]
        [Display(Name = "Phone Number")]
        public string? EmergencyContactPhone { get; set; }

        public string UserType { get; set; } = null!;

        public virtual ICollection<Pet> Pets { get; set; }
    }
}

2ndYear/HVK_Reservation_Project/HVK/Controllers/HvkuserController.cs
using HVK.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;

namespace HVK.Controllers
{
    public class HvkuserController : Controller
    {
        private readonly HVKW24_Team3Context _context;
        public HvkuserController(HVKW24_Team3Context context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "customer")]
        public IActionResult CustomerHome()
        {
            int hvkuserId = (int)HttpContext.Session.GetInt32("userid");
            var customer = _context.Hvkusers
                                 .Include(u => u.Pets)
                                 .ThenInclude(p => p.PetReservations)
                                 .ThenInclude(pr => pr.Reservation)
                                  .FirstOrDefault(u => u.HvkuserId == hvkuserId);
            return View(customer);
        }
        [Authorize(Roles = "employee")]
        public IActionResult EmployeeHome()
        {
            int hvkuserId = (int)HttpContext.Session.GetInt32("userid");
            var employee = _context.Hvkusers.FirstOrDefault(u => u.HvkuserId == hvkuserId);
            var pets = _context.Pets
                            .Include(p => p.Hvkuser)
                            .Include(p => p.PetReservations)
                            .ThenInclude(pr => pr.Reservation)
                            .ToList();
            var viewModel = new EmployeeHomeViewModel
            {
                Employee = employee,
                Pets = pets
            };

            return View(viewModel);
        }

        [Authorize(Roles = "employee")]
        public IActionResult AllCustomers(string? search)
        {
            IQueryable<HVK.Models.Hvkuser> customerList = _context.Hvkusers.Where(u => u.UserType.ToLower() == "customer");
            if (!string.IsNullOrEmpty(search))
            {
                customerList = customerList.Where(u => u.LastName.Contains(search) || u.Email.Contains(search) || u.Phone.Contains(search) || u.CellPhone.Contains(search));
            }
            List<HVK.Models.Hvkuser> res = customerList.OrderBy(u => u.LastName).ToList();
            return View(res);
        }

        [Authorize(Roles = "employee,customer")]
        public IActionResult CustomerDetails(int id)
        {
            var customer = _context.Hvkusers
                            .Include(u => u.Pets)
                            .ThenInclude(p => p.PetReservations)
                            .ThenInclude(pr => pr.Reservation)
                            .FirstOrDefault(u => u.HvkuserId == id);
            if (customer != null)
                return View(customer);
            return RedirectToAction("Index", "Home");
        }
        public IActionResult ManageCustomer()
        {
            ViewBag.Type = HttpContext.Session.GetString("usertype").ToString();
            return View();
        }

        [Authorize(Roles = "employee,customer")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Hvkusers == null)
            {
                return NotFound();
            }

            var hvkuser = await _context.Hvkusers.FindAsync(id);
            if (hvkuser == null)
            {
                return NotFound();
            }
            return View(hvkuser);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "employee,customer")]
        public async Task<IActionResult> Edit(int id, [Bind("HvkuserId,FirstName,LastName,Email,Password,Street,City,Province,PostalCode,Phone,CellPhone,EmergencyContactFirstName,EmergencyContactLastName,EmergencyContactPhone,UserType")] Hvkuser hvkuser)
        {
            if (id != hvkuser.HvkuserId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(hvkuser);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HvkuserExists(hvkuser.HvkuserId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                if (hvkuser.UserType.ToLower() == "employee")
                    return RedirectToAction("EmployeeHome");
                return RedirectToAction("CustomerHome");
            }
            return View(hvkuser);
        }

        private bool HvkuserExists(int id)
        {
            return (_context.Hvkusers?.Any(e => e.HvkuserId == id)).GetValueOrDefault();
        }

        [HttpGet]
        [Authorize(Roles = "employee,customer")]
        public IActionResult CreateCustomer()
        {
            TempData.Keep();
            return View();
        }
        [HttpPost]
        [Authorize(Roles = "employee,customer")]
        public async Task<IActionResult> CreateCustomer(Hvkuser user)
        {
            if (ModelState.IsValid)
            {
                _context.Add(user);
                await _context.SaveChangesAsync();
                if (HttpContext.Session.GetString("usertype").ToString() == "customer")
                    return RedirectToAction(nameof(CustomerHome));
                if (HttpContext.Session.GetString("usertype").ToString() == "employee")
                    return RedirectToAction(nameof(EmployeeHome));
            }
            return View(user);
        }


    }
}

2ndYear/HVK_Reservation_Project/HVK/Views/Hvkuser/AllCustomers.cshtml
@inject HVK.Models.FormattingService DFormat
@model IEnumerable<HVK.Models.Hvkuser>
@await Html.PartialAsync("_Navigation")

<main>
    <h1 class="display-5 text-center">All Customers</h1>
    <form action="@Url.Action("AllCustomers", "Hvkuser")" method="get" class="side-by-side">
        <input type="text" name="search" placeholder="Search by last name, email or phone" class="form-control search">
        <button class="btn" id="search" type="submit"><img src="~/images/find.png" alt="Magnifying glass" /></button>
    </form>
    <p class="text-center">Can't find a customer? @Html.ActionLink("New Customer", "CreateCustomer", "Hvkuser")</p>
    <table class="table table-bordered">
        <tr class="bg-dark text-white">
            <th>Name</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Cell Phone</th>
            <th>View Profile</th>
            <th>New Pet</th>
            <th>New Reservation</th>
        </tr>
        @foreach (var c in Model) {
            <tr class="bg-white">
                <td>@c.FirstName @c.LastName</td>
                <td>@(c.Email == null ? "N/A" : c.Email)</td>
                <td>@DFormat.PhoneDisplay(c.Phone)</td>
                <td>@DFormat.PhoneDisplay(c.CellPhone)</td>
                <td><a asp-action="CustomerDetails" asp-controller="Hvkuser" asp-route-id="@c.HvkuserId" class="a-view-profile">View Profile</a></td>
                <td><a asp-action="Create" asp-controller="Pet" class="a-new-pet" asp-route-id="@c.HvkuserId">New Pet</a></td>
                <td><a asp-action="Create" asp-controller="Reservation" class="a-new-reservation" asp-route-id="@c.HvkuserId">New Reservation</a></td>
            </tr>
        }
    </table>
</main>

2ndYear/HVK_Reservation_Project/HVK/Views/Hvkuser/CreateCustomer.cshtml
@model HVK.Models.Hvkuser
@{
    var usertype = Context.Session?.GetString("usertype")?.ToLower() ?? "";

}
@if (usertype == "employee") {
    
    @await Html.PartialAsync("_Navigation")
}
<h1 class="display-5 text-center">New Customer</h1>
<form asp-controller="Hvkuser">
    <fieldset>
        <legend>Contact Information</legend>
        <div>
            <div class="form-group">
                @* <div asp-validation-summary="All" class="text-danger"></div> *@
                <label asp-for="FirstName"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="LastName"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Email"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="CellPhone"></label>
                <input asp-for="CellPhone" class="form-control" />
                <span asp-validation-for="CellPhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password"></label>
                <input asp-for="Password" type="password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
          @*   <div class="form-group">
                <label asp-for="Password">Re-enter password</label>
                <input asp-for="Password" type="password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div> *@
        </div>
    </fieldset>
    <fieldset>
        <legend>Address Information</legend>
        <div>
            <div class="form-group">
                <label asp-for="Street"></label>
                <input asp-for="Street" class="form-control" />
                <span asp-validation-for="Street" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="City"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Province"></label>
                <select asp-for="Province" class="form-control">
                    <option value="ON">ON</option>
                    <option value="QC" selected>QC</option>
                </select>
                <span asp-validation-for="Province" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="PostalCode"></label>
                <input asp-for="PostalCode" class="form-control" />
                <span asp-validation-for="PostalCode" class="text-danger"></span>
            </div>
        </div>
    </fieldset>
    <fieldset>
        <legend>Emergency Contact</legend>
        <div>
            <div class="form-group">
                <label asp-for="EmergencyContactFirstName"></label>
                <input asp-for="EmergencyContactFirstName" class="form-control" />
                <span asp-validation-for="EmergencyContactFirstName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="EmergencyContactLastName"></label>
                <input asp-for="EmergencyContactLastName" class="form-control" />
                <span asp-validation-for="EmergencyContactLastName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="EmergencyContactPhone"></label>
                <input asp-for="EmergencyContactPhone" class="form-control" />
                <span asp-validation-for="EmergencyContactPhone" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="UserType" value="Customer" />
        </div>
    </fieldset>
    @if (usertype == "employee") {
        <button type="button">@Html.ActionLink("Cancel", "EmployeeHome", "Hvkuser")</button>
    } else {
        <button type="button">@Html.ActionLink("Cancel", "Login", "Account")</button>
    }

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

2ndYear/HVK_Reservation_Project/HVK/Views/Hvkuser/CustomerDetails.cshtml
@inject HVK.Models.FormattingService DFormat
@model HVK.Models.Hvkuser
@await Html.PartialAsync("_Navigation")
@{
    var reservations = Model.Pets.SelectMany(p => p.PetReservations)
                                .GroupBy(pr => pr.ReservationId)
                                .OrderBy(pr => pr.First().Reservation.StartDate)
                                .ThenBy(pr => pr.First().Reservation.EndDate);
}
<main>
    <h1 class="display-5 text-center">Customer Details</h1>
    <div class="card p-3 details">
        <div class="side-by-side">
            <h1 class="display-6 text-center">@(Model.FirstName != null && Model.LastName != null ? Model.FirstName + " " + Model.LastName : "N/A")</h1>
            <a asp-action="Edit" asp-route-id="@Model?.HvkuserId" class="text-center">Edit</a>
        </div>
        <div class="detail-inside">
            <div class="details-grid">
                <div class="details-item">
                    <p><b>Email:</b> @(Model.Email != null ? Model.Email : "N/A")</p>
                    <p><b>Phone Number:</b> @DFormat.PhoneDisplay(Model.Phone)</p>
                    <p><b>Cell Phone Number:</b> @DFormat.PhoneDisplay(Model.CellPhone)</p>
                    <p><b>Emergency Contact Name:</b> @(Model.EmergencyContactFirstName != null && Model.EmergencyContactLastName != null ? Model.EmergencyContactFirstName + " " + Model.EmergencyContactLastName : "N/A")</p>
                    <p><b>Emergency Contact Phone Number:</b> @DFormat.PhoneDisplay(Model.EmergencyContactPhone)</p>
                </div>
                <div class="details-item">
                    <p><b>Street:</b> @(Model.Street != null ? Model.Street : "N/A")</p>
                    <p><b>City:</b> @(Model.City != null ? Model.City : "N/A")</p>
                    <p><b>Province:</b> @(Model.Province != null ? Model.Province : "N/A")</p>
                    <p><b>Postal Code:</b> @DFormat.PostalDisplay(Model.PostalCode)</p>
                </div>
            </div>
            <h5 class="display-7"><b>Pets</b></h5>
            <a asp-action="Create" asp-controller="Pet" class="a-new-pet" asp-route-id="@Model.HvkuserId">New Pet</a>
            <table class="table table-bordered pet-table">
                <tr class="bg-dark text-white">
                    <th>Name</th>
                    <th>Details</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
                @foreach (var pet in Model.Pets) {
                    <tr class="bg-white">
                        <td>@pet.Name</td>
                        <td>@Html.ActionLink("Details", "PetDetails", "Pet", new { id = pet.PetId }, null)</td>
                        <td>@Html.ActionLink("Edit", "Edit", "Pet", new { id = pet.PetId }, null)</td>
                        <td>@Html.ActionLink("Remove", "Delete", "Pet", new { id = pet.PetId }, null)</td>
                    </tr>
                }
            </table>
            <h5 class="display-7"><b>Reservations</b></h5>
            <a asp-action="Create" asp-controller="Reservation" class="a-new-reservation" asp-route-id="@Model.HvkuserId">New Reservation</a>
            @if (reservations.Count() == 0)
            {
                <p>No reservations found.</p>
            }
            else
            {
                <table class="table table-bordered">
                    <tr class="bg-dark text-white">
                        <th>Start Date</th>
                        <th>End Date</th>
                        <th>Pets</th>
                        <th>Edit</th>
                        <th>Cancel</th>
                    </tr>
                    @foreach (var pr in reservations)
                    {
                        var res = pr.First().Reservation;
                        var pets = pr.Select(pr => pr.Pet.Name);
                        <tr class="bg-white">
                            <td>@res.StartDate.ToString("yyyy/MM/dd")</td>
                            <td>@res.EndDate.ToString("yyyy/MM/dd")</td>
                            <td>@string.Join(", ", pets)</td>
                            <td><a asp-action="Edit" asp-controller="Reservation" asp-route-id="@res.ReservationId">Edit</a></td>
                            <td><a asp-action="Delete" asp-controller="Reservation" asp-route-id="@res.ReservationId">Cancel</a></td>
                        </tr>
                    }
                </table>
                <br />
            }
        </div>
    </div>
</main>

2ndYear/HVK_Reservation_Project/HVK/Views/Hvkuser/CustomerHome.cshtml
@model HVK.Models.Hvkuser
@{
    ViewData["HvkuserId"] = Model.HvkuserId;
}
@await Html.PartialAsync("_Navigation")
@{
    var reservations = Model.Pets.SelectMany(p => p.PetReservations)
                                .GroupBy(pr => pr.ReservationId)
                                .OrderBy(pr => pr.First().Reservation.StartDate)
                                .ThenBy(pr => pr.First().Reservation.EndDate);

    TempData.Keep();
}
<main>
    <div class="text-center">
        <h1 class="display-5">Welcome Back, @Model.FirstName!</h1>
        <a asp-action="CustomerDetails" asp-route-id="@Model.HvkuserId" id="my-account-btn">
            My Account
        </a>
    </div>
    <h2 class="display-7">My Pets</h2>
    <table class="table table-bordered pet-table">
        <tr class="bg-dark text-white">
            <th>Name</th>
            <th>Details</th>
            <th>Edit</th>
            <th>Remove</th>
        </tr>
        @foreach (var pet in Model.Pets)
        {
            <tr class="bg-white">
                <td>@pet.Name</td>
                <td>@Html.ActionLink("Details", "PetDetails", "Pet", new { id = pet.PetId }, null)</td>
                <td>@Html.ActionLink("Edit", "Edit", "Pet", new { id = pet.PetId }, null)</td>
                <td>@Html.ActionLink("Remove", "Delete", "Pet", new { id = pet.PetId }, null)</td>
            </tr>
        }
    </table>
    <h2 class="display-7">My Reservations</h2>
    @if (reservations.Count() == 0) {
        <p>No reservations found.</p>
    } else {
        <table class="table table-bordered">
            <tr class="bg-dark text-white">
                <th>Start Date</th>
                <th>End Date</th>
                <th>Pets</th>
                <th>Edit</th>
                <th>Cancel</th>
            </tr>
            @foreach (var pr in reservations) {
                var res = pr.First().Reservation;
                var pets = pr.Select(pr => pr.Pet.Name);
                <tr class="bg-white">
                    <td>@res.StartDate.ToString("yyyy/MM/dd")</td>
                    <td>@res.EndDate.ToString("yyyy/MM/dd")</td>
                    <td>@string.Join(", ", pets)</td>
                    <td><a asp-action="Edit" asp-controller="Reservation" asp-route-id="@res.ReservationId">Edit</a></td>
                    <td><a asp-action="Delete" asp-controller="Reservation" asp-route-id="@res.ReservationId">Cancel</a></td>
                </tr>
            }
        </table>
    }

</main>

2ndYear/HVK_Reservation_Project/HVK/Views/Hvkuser/Edit.cshtml
@model HVK.Models.Hvkuser
@await Html.PartialAsync("_Navigation")
@{
    ViewData["Title"] = "Edit";
}

<h1 class="display-5 text-center">Edit Customer</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="HvkuserId" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Street" class="control-label"></label>
                <input asp-for="Street" class="form-control" />
                <span asp-validation-for="Street" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Province" class="control-label"></label>
                <input asp-for="Province" class="form-control" />
                <span asp-validation-for="Province" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PostalCode" class="control-label"></label>
                <input asp-for="PostalCode" class="form-control" />
                <span asp-validation-for="PostalCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CellPhone" class="control-label"></label>
                <input asp-for="CellPhone" class="form-control" />
                <span asp-validation-for="CellPhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmergencyContactFirstName" class="control-label"></label>
                <input asp-for="EmergencyContactFirstName" class="form-control" />
                <span asp-validation-for="EmergencyContactFirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmergencyContactLastName" class="control-label"></label>
                <input asp-for="EmergencyContactLastName" class="form-control" />
                <span asp-validation-for="EmergencyContactLastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmergencyContactPhone" class="control-label"></label>
                <input asp-for="EmergencyContactPhone" class="form-control" />
                <span asp-validation-for="EmergencyContactPhone" class="text-danger"></span>
            </div>
                <input type="hidden" asp-for="UserType" value="Customer"/>
                <br />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>